{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChainableException"},{"kind":"text","text":" : AnyObject, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/chainableexception"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/s5ErrorP","doc:\/\/org.cocoapods.ExpoModulesCore\/s8SendableP"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/AppContextLost","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/FileSystemModuleNotFound","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/PermissionsModuleNotFound","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/RuntimeLost","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/SimulatorNotSupported","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/ViewNotFound","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/GenericException","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/UnexpectedException"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An exception that may have been caused by another error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChainableException"}],"title":"ChainableException","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:15ExpoModulesCore18ChainableExceptionP","modules":[{"name":"ExpoModulesCore"}],"navigatorTitle":[{"kind":"identifier","text":"ChainableException"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/cause","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/rootCause-1u9cn"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/causedBy(_:)-8vil4","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/isCausedBy(_:)-967bo"]}],"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/causedBy(_:)-8vil4":{"defaultImplementations":1,"role":"symbol","title":"causedBy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets the direct cause of the exception and returns itself."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/causedBy(_:)-8vil4","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/causedby(_:)-8vil4"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException":{"role":"symbol","title":"ChainableException","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChainableException"}],"abstract":[{"type":"text","text":"An exception that may have been caused by another error."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChainableException"}],"url":"\/documentation\/expomodulescore\/chainableexception"},"doc://org.cocoapods.ExpoModulesCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/s8SendableP"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/FileSystemModuleNotFound":{"role":"symbol","title":"Exceptions.FileSystemModuleNotFound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileSystemModuleNotFound"}],"abstract":[{"type":"text","text":"An exception to throw when there is no module implementing the "},{"type":"codeVoice","code":"EXFileSystemInterface"},{"type":"text","text":" interface."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/FileSystemModuleNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileSystemModuleNotFound"}],"url":"\/documentation\/expomodulescore\/exceptions\/filesystemmodulenotfound"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/RuntimeLost":{"role":"symbol","title":"Exceptions.RuntimeLost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RuntimeLost"}],"abstract":[{"type":"text","text":"The JavaScript runtime is no longer available."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/RuntimeLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RuntimeLost"}],"url":"\/documentation\/expomodulescore\/exceptions\/runtimelost"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/UnexpectedException":{"role":"symbol","title":"UnexpectedException","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnexpectedException"}],"abstract":[{"type":"text","text":"Exception wrapper used to handle unexpected internal native errors."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/UnexpectedException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnexpectedException"}],"url":"\/documentation\/expomodulescore\/unexpectedexception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/ViewNotFound":{"role":"symbol","title":"Exceptions.ViewNotFound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewNotFound"}],"abstract":[{"type":"text","text":"An exception to throw when the view with the given tag and class cannot be found."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/ViewNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewNotFound"}],"url":"\/documentation\/expomodulescore\/exceptions\/viewnotfound"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/cause":{"role":"symbol","title":"cause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The direct cause of the exception."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/cause","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/cause"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/isCausedBy(_:)-967bo":{"defaultImplementations":1,"role":"symbol","title":"isCausedBy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCausedBy"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"ErrorType"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"ErrorType","preciseIdentifier":"s:15ExpoModulesCore18ChainableExceptionP10isCausedByySbqd__ms5ErrorRd__lF0I4TypeL_qd__mfp"},{"kind":"text","text":".Type) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Tells whether any of the cause in chain is of given type."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/isCausedBy(_:)-967bo","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/iscausedby(_:)-967bo"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/PermissionsModuleNotFound":{"role":"symbol","title":"Exceptions.PermissionsModuleNotFound","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PermissionsModuleNotFound"}],"abstract":[{"type":"text","text":"An exception to throw when there is no module implementing the "},{"type":"codeVoice","code":"EXPermissionsInterface"},{"type":"text","text":" interface."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/PermissionsModuleNotFound","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PermissionsModuleNotFound"}],"url":"\/documentation\/expomodulescore\/exceptions\/permissionsmodulenotfound"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/AppContextLost":{"role":"symbol","title":"Exceptions.AppContextLost","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppContextLost"}],"abstract":[{"type":"text","text":"The Expo app context is no longer available."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/AppContextLost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppContextLost"}],"url":"\/documentation\/expomodulescore\/exceptions\/appcontextlost"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exceptions/SimulatorNotSupported":{"role":"symbol","title":"Exceptions.SimulatorNotSupported","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SimulatorNotSupported"}],"abstract":[{"type":"text","text":"An exception to throw when the operation is not supported on the simulator."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exceptions\/SimulatorNotSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SimulatorNotSupported"}],"url":"\/documentation\/expomodulescore\/exceptions\/simulatornotsupported"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/GenericException":{"role":"symbol","title":"GenericException","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GenericException"}],"abstract":[{"type":"text","text":"The exception that needs some additional parameters to be best described."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/GenericException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GenericException"}],"url":"\/documentation\/expomodulescore\/genericexception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception":{"role":"symbol","title":"Exception","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Exception"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Exception"}],"url":"\/documentation\/expomodulescore\/exception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ChainableException/rootCause-1u9cn":{"defaultImplementations":1,"role":"symbol","title":"rootCause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The first error that started the chain of exceptions."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ChainableException\/rootCause-1u9cn","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/expomodulescore\/chainableexception\/rootcause-1u9cn"},"doc://org.cocoapods.ExpoModulesCore/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/s5ErrorP"}}}