{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExceptionOrigin"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/exceptionorigin"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/s23CustomStringConvertibleP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ExceptionOrigin","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Represents the place in code where the exception was created."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExceptionOrigin"}],"title":"ExceptionOrigin","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:15ExpoModulesCore15ExceptionOriginV","modules":[{"name":"ExpoModulesCore"}],"navigatorTitle":[{"kind":"identifier","text":"ExceptionOrigin"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ExceptionOrigin\/description"]}],"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ExceptionOrigin/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Stringified representation of the exception origin."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ExceptionOrigin\/description","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/exceptionorigin\/description"},"doc://org.cocoapods.ExpoModulesCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/ExceptionOrigin":{"role":"symbol","title":"ExceptionOrigin","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExceptionOrigin"}],"abstract":[{"type":"text","text":"Represents the place in code where the exception was created."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/ExceptionOrigin","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExceptionOrigin"}],"url":"\/documentation\/expomodulescore\/exceptionorigin"}}}