{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expomodulescore\/unexpectedexception\/reason"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/UnexpectedException\/reason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"String describing the reason of the exception."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"reason","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:15ExpoModulesCore19UnexpectedExceptionC6reasonSSvp","modules":[{"name":"ExpoModulesCore"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/UnexpectedException"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/UnexpectedException":{"role":"symbol","title":"UnexpectedException","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnexpectedException"}],"abstract":[{"type":"text","text":"Exception wrapper used to handle unexpected internal native errors."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/UnexpectedException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnexpectedException"}],"url":"\/documentation\/expomodulescore\/unexpectedexception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/UnexpectedException/reason":{"role":"symbol","title":"reason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"String describing the reason of the exception."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/UnexpectedException\/reason","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/unexpectedexception\/reason"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"}}}