{"variants":[{"paths":["\/documentation\/expomodulescore\/exception\/chainableexception-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/ChainableException-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/rootCause"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/causedBy(_:)","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/isCausedBy(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"ExpoModulesCore"}],"role":"collectionGroup","title":"ChainableException Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception"]]},"references":{"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception/causedBy(_:)":{"role":"symbol","title":"causedBy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"causedBy"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Sets the direct cause of the exception and returns itself."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/causedBy(_:)","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/exception\/causedby(_:)"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore":{"role":"collection","title":"ExpoModulesCore","abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception/isCausedBy(_:)":{"role":"symbol","title":"isCausedBy(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCausedBy"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"ErrorType"},{"kind":"text","text":">("},{"kind":"typeIdentifier","text":"ErrorType","preciseIdentifier":"s:15ExpoModulesCore18ChainableExceptionPAAE10isCausedByySbqd__ms5ErrorRd__lF0I4TypeL_qd__mfp"},{"kind":"text","text":".Type) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Tells whether any of the cause in chain is of given type."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/isCausedBy(_:)","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/exception\/iscausedby(_:)"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception":{"role":"symbol","title":"Exception","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Exception"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Exception"}],"url":"\/documentation\/expomodulescore\/exception"},"doc://org.cocoapods.ExpoModulesCore/documentation/ExpoModulesCore/Exception/rootCause":{"role":"symbol","title":"rootCause","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootCause"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The first error that started the chain of exceptions."}],"identifier":"doc:\/\/org.cocoapods.ExpoModulesCore\/documentation\/ExpoModulesCore\/Exception\/rootCause","kind":"symbol","type":"topic","url":"\/documentation\/expomodulescore\/exception\/rootcause"}}}